apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: admin-application-virtualservice
  namespace: canary
spec:
  hosts:
  - admin-application
  http:
  - route:
    - destination:
        host: admin-application
        subset: admin-application-v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: admin-application-dr
  namespace: canary
spec:
  host: admin-application
  subsets:
  - name: admin-application-v1
    labels:
      version: admin-application-v1
