apiVersion: v1
kind: Service
metadata:
  name: admin-application-service
  namespace: default
  labels:
    name: admin-application-service
spec:
  type: NodePort
  ports:
  - port: 9401
    nodePort: 30004
    targetPort: 9401
    protocol: TCP

  selector:
    name: admin-application
    deploymentType: GREEN
